name: Felipe Vieira
email: nvieirafelipe@gmail.com

# Build settings
exclude: [ 'Gemfile*', 'README.md', 'bower.json' ]
highlighter: rouge
markdown: kramdown
sass:
  style: :compressed
  sass_dir: assets/stylesheets

gem:
  - jekyll-babel
