name: Felipe Vieira
email: nvieirafelipe@gmail.com

# Build settings
exclude:
  - bower.json
  - Dockerfile
  - docker-compose
  - package*.json
  - Gemfile*
  - node_modules
  - README.md
  - src
  - vendor
  - webpack.config.js
